name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  c-Tests:
     runs-on: ubuntu-latest
     steps:
      - run: echo "coming soon"

  web-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js

        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install linters

        run: npm install --global eslint stylelint
      - name: Run ESLint (JS)
        run: eslint "**/*.js" || true

      - name: Run Stylelint (CSS)
        run: stylelint "**/*.css" || true

      - run: echo "linting done"

  summary-job:
    runs-on: ubuntu-latest

    # collect logs from the other jobs and aggregate them here
    steps:
      - run: echo "coming soon"
        
