name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:

jobs:

  c-Tests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: install CUnit
       run: sudo apt-get update && sudo apt-get install -y libcunit1-dev make gcc

     - name: build & run tests
       run: make -C tests_demo run


  c-Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install clang-tidy
          run: sudo apt-get install -y clang-tidy

        - name: Run clang-tidy on all C files
          run: | 
            find . -name "*.c" -print0 | xargs -0 clang-tidy


  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci # or yarn install
      - uses: sibiraj-s/action-eslint@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          

  web-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js

        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install linters

        run: npm install --save-dev eslint stylelint eslint-formatter-github

      - name: Run ESLint (JS)
        run: npx eslint "**/*.js" --format github #|| true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Stylelint (CSS)
        run: stylelint "**/*.css" #|| true

      - run: echo "linting done"


  summary-job:
    runs-on: ubuntu-latest

    # collect logs from the other jobs and aggregate them here
    steps:
      - run: echo "coming soon"
        

